name: bebe
description: An app for tracking baby things.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  decimal: ^2.2.0
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_portal: ^1.1.1
  flutter_riverpod: ^2.0.0-dev.9
  flutter_secure_storage: ^6.0.0
  freezed_annotation: ^2.1.0
  go_router: ^5.0.1
  intl: ^0.17.0
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  reactive_date_time_picker: ^0.5.0
  reactive_forms: ^14.1.0
  shared_preferences: ^2.0.15
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1

flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
